project:
  type: website

website:
  title: "DeclareDesign"
  navbar:
    logo: static/dd-logo-sm.svg
    right:
      - text: "Getting started"
        href: getting-started.html
      - text: Book
        href: https://book.declaredesign.org
      - text: Software
        menu: 
          - text: fabricatr
            href: fabricatr/
          - text: randomizr
            href: randomizr/
      - text: Blog
        href: blog.html
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css



